version: "3"
services:
  cloudwork:
    container_name:
      cloudwork_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - /var/cloudwork/log:/log
    networks:
      - cloudnet
    depends_on:
      - database

  frontend:
    container_name:
      cloudwork_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - cloudnet
    restart:
      always

  database:
    container_name:
      db_mysql
    image:
      mysql
    ports:
      - "3306:3306"
    networks:
      - cloudnet
    volumes:
      - /var/mysql_data:/var/lib/mysql
    command:
      - "--max-allowed-packet=814743552"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: word
      MYSQL_DATABASE: storage
    restart:
      always

networks:
  cloudnet:
