server:
  port: 9090
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storage?createDatabaseIfNotExist=true
    username: root
    password: fuck

  sql:
    init:
      continue-on-error: true
      mode: always

  liquibase:
    enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
