server:
  port: 9090
  error:
    include-message: always
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storage?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: word

  sql:
    init:
      continue-on-error: true
      mode: always

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 777MB
      max-request-size: 777MB

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

logging:
  level:
    org.springframework: INFO
    ru.netology: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: ./log/cloudwork.log

application:
  user-preloader:
    enabled: false
  front-url: >
    http://localhost:8080,
    http://localhost:8081
  token-header: "auth-token"
  token-prefix: "Bearer "