server:
  port: 9090
  error:
    include-message: always
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storage?createDatabaseIfNotExist=true
    username: root
    password: fuck

  sql:
    init:
      continue-on-error: true
      mode: always

  liquibase:
    enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework: INFO
    ru.netology: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: ./log/cloudwork.log