server:
  port: 9090
  error:
    include-message: always
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storage?createDatabaseIfNotExist=true
    username: root
    password: fuck

  sql:
    init:
      continue-on-error: true
      mode: always

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 777MB
      max-request-size: 777MB

logging:
  level:
    org.springframework: INFO
    ru.netology: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: ./log/cloudwork.log

application:
  user-preloader:
    enabled: true
  front-url: >
    "http://localhost:8080",
    "http://localhost:8081"
  token-header: "auth-token"
  token-prefix: "Bearer "